### ISSUE TITLE
About windows - License CC BY 3.0 DEED outdated

### ISSUE THREAD

**Issue by bovirus** [GustavLindberg99/AndroidDrive#11]
@GustavLindberg99 

In About window the link about CC BY 3.0 DEED livcense point a web page

https://creativecommons.org/licenses/by/3.0/

that report that this license is outdated.

Could be possible to ask to the icon author to switch to CC BY 4.0 DEED licnse?

Thanks.

**Comment by GustavLindberg99** [comment]
I'm fine with using CC BY 3.0, so I don't see much point in doing that. If you would like to use their icons, I suggest to ask them to add a CC BY 4.0 license yourself.
