### ISSUE TITLE
Improvemnt - Change exe and zip file name

### ISSUE THREAD

**Issue by bovirus** [GustavLindberg99/AndroidDrive#13]
@GustavLindberg99 

I propose to change the exe /zip file with these names

- AndroidDrive-Install.exe
- AndroidDrive-Portable.zip

Simple and clear.
I prefer "AndroidDrive-Install.exe" the "AndroidDrive-setup.exe" because for me is more clear.

**Comment by GustavLindberg99** [comment]
That's a good idea. I changed it to do that.

**Comment by bovirus** [comment]
@GustavLindberg99 

OK,. Thanks.
Please close the issue.
