### ISSUE TITLE
Improvement - Use GPL 3.0 license as .rtf instead .txt

### ISSUE THREAD

**Issue by bovirus** [GustavLindberg99/AndroidDrive#14]
@GustavLindberg99 

Please consider to modify the installer script to use for GPL 3.0 license the rtf file 

https://www.gnu.org/licenses/gpl-3.0.rtf

instead current .txt file

Please check screenshot with new RTF GNU 3.0 license.

![image](https://github.com/GustavLindberg99/AndroidDrive/assets/1262554/4546bd75-c321-4f4a-a9f9-f6b02f8ca659)

**Comment by GustavLindberg99** [comment]
Done.
