### ISSUE TITLE
Feature Request: Make a 32 bit version too, for older systems.

### ISSUE THREAD

**Issue by ibay770** [GustavLindberg99/AndroidDrive#16]
Many thanks for making this! Greatly appreciated! 
Would it be possible to make a 32 bit version for older systems/OSes?
Thanks in advamce.

**Comment by GustavLindberg99** [comment]
I just tried to see if it's possible, but unfortunately there's no easy way of doing that. To compile a 32 bit version of AndroidDrive would require me to install 32 bit versions of Qt and Dokan, which is very difficult, especially since there is no 32 bit version of Qt 6.

**Comment by ibay770** [comment]
Aha I understand.  Would an older version of qt work?  
Regardless thank you again for making this.

**Comment by GustavLindberg99** [comment]
Qt 5 would work, but I would have to rewrite parts of my code to make it compatible with Qt 5, and I wouldn't be able to use any new Qt features. Also there would still be the issue of installing a 32 bit version of Dokan, which would conflict with the 64 bit version I already have installed.

**Comment by ibay770** [comment]
If you're willing to do the rewriting. I'm happy to test it out on my 32 bit, win7 VM with dokan on it.

**Comment by GustavLindberg99** [comment]
It would be difficult to rewrite the current version to be fully compatible with Qt 5, but older versions of AndroidDrive used Qt 5, so you can download the source code from an older version and compile it yourself. To download the source code for AndroidDrive 2.0.6 (which is the last version of AndroidDrive to use Qt 5), you can run the following commands in the command line:

```
git clone https://github.com/GustavLindberg99/AndroidDrive
git checkout a36e464a665bafd11866644507b5e900ef8c0e90
```

If you manage to compile a 32-bit version, it would be nice if you could share it so that I can upload it for others to use.

**Comment by ibay770** [comment]
I would be happy too. I installed the 32bit version of qt 5 on my 32bit machine,  now I'm just trying to figure out how to compile it.

**Comment by GustavLindberg99** [comment]
Once you've downloaded the source code as I explained above, to compile it, you need to open AndroidDrive.pro in Qt Creator and click on the green arrow on the bottom left.

Depending on where Dokan is installed, you might also need to edit the `INCLUDEPATH` and `LIBS` entries in AndroidDrive.pro. In particular, a 32 bit computer probably doesn't have a folder called `C:/Program Files (x86)`>

**Comment by ibay770** [comment]
OK perfect! Thank you, I'll work on that and keep you posted.

**Comment by ibay770** [comment]
Tried making those adjustments, getting a bunch of errors.

C:\Users\Administrator\AndroidDrive\sources\settingswindow.cpp:47: error: no matching member function for call to 'connect'

I have the 32/64 bit compilers for windows installed in qt.
Do I need to download any Windows Kits?

**Comment by GustavLindberg99** [comment]
You probably do need to download windows kits, but that's not the problem here. You seem to be compiling the current Qt 6 version of AndroidDrive instead of the old Qt 5 version. Did you run `git checkout a36e464a665bafd11866644507b5e900ef8c0e90`?

**Comment by ibay770** [comment]
Thank you, yes I tried the first command, cd into the folder, tried teh checkout command, it gave me this message:
You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

Sam problem, when building it gives 32 errors, 
C:\Users\Administrator\Documents\AndroidDrive\sources\settingswindow.h:26: error: 'Settings' does not name a type
In file included from ..\sources\devicelistwindow.h:11:0,
                 from ..\sources\main.cpp:6:
..\sources\settingswindow.h:26:12: error: 'Settings' does not name a type
     friend Settings &operator<<(Settings &settings, const SettingsWindow *settingsWindow);
            ^~~~~~~~

Thanks in advance and sorry for the hassle.

**Comment by GustavLindberg99** [comment]
Try adding `class Settings;` on line 16 of settingswindow.h.
