### ISSUE TITLE
pixel 7 and galaxy s8 connectd with USB returned error

### ISSUE THREAD

**Issue by anmac1789** [GustavLindberg99/AndroidDrive#17]
hello this is the error I got as soon as I started android drive. What does this mean ? I have dokan library installed but I still got this error.

![image](https://github.com/GustavLindberg99/AndroidDrive/assets/103609429/d4ab0973-fea4-4635-9cd2-411cd8086099)

**Comment by GustavLindberg99** [comment]
Which version of AndroidDrive are you using? If you don't know, right click on the AndroidDrive icon in the task bar and choose "About AndroidDrive", and it will tell you the version.

**Comment by anmac1789** [comment]
> Which version of AndroidDrive are you using? If you don't know, right click on the AndroidDrive icon in the task bar and choose "About AndroidDrive", and it will tell you the version.

I'm using 2.1.1.0

**Comment by GustavLindberg99** [comment]
Are you sure? There is no place in the code for version 2.1.1 that can give the error message in your screenshot. There are only three places in the code for version 2.1.1 that can give an error message at all: [line 91 of devicelistwindow.cpp](https://github.com/GustavLindberg99/AndroidDrive/blob/main/sources/devicelistwindow.cpp#L91), [line 199 of devicelistwindow.cpp](https://github.com/GustavLindberg99/AndroidDrive/blob/main/sources/devicelistwindow.cpp#L199) and [line 233 of devicelistwindow.cpp](https://github.com/GustavLindberg99/AndroidDrive/blob/main/sources/devicelistwindow.cpp#L233), none of which start with "An error occurred when reading device".

So I'm quite sure your screenshot is from an older version. If so, do you still get an error in version 2.1.1? If you do, can you post a screenshot from that version?

**Comment by anmac1789** [comment]
> Are you sure? There is no place in the code for version 2.1.1 that can give the error message in your screenshot. There are only three places in the code for version 2.1.1 that can give an error message at all: [line 91 of devicelistwindow.cpp](https://github.com/GustavLindberg99/AndroidDrive/blob/main/sources/devicelistwindow.cpp#L91), [line 199 of devicelistwindow.cpp](https://github.com/GustavLindberg99/AndroidDrive/blob/main/sources/devicelistwindow.cpp#L199) and [line 233 of devicelistwindow.cpp](https://github.com/GustavLindberg99/AndroidDrive/blob/main/sources/devicelistwindow.cpp#L233), none of which start with "An error occurred when reading device".
> 
> So I'm quite sure your screenshot is from an older version. If so, do you still get an error in version 2.1.1? If you do, can you post a screenshot from that version?

I will try

**Comment by anmac1789** [comment]
> Are you sure? There is no place in the code for version 2.1.1 that can give the error message in your screenshot. There are only three places in the code for version 2.1.1 that can give an error message at all: [line 91 of devicelistwindow.cpp](https://github.com/GustavLindberg99/AndroidDrive/blob/main/sources/devicelistwindow.cpp#L91), [line 199 of devicelistwindow.cpp](https://github.com/GustavLindberg99/AndroidDrive/blob/main/sources/devicelistwindow.cpp#L199) and [line 233 of devicelistwindow.cpp](https://github.com/GustavLindberg99/AndroidDrive/blob/main/sources/devicelistwindow.cpp#L233), none of which start with "An error occurred when reading device".
> 
> So I'm quite sure your screenshot is from an older version. If so, do you still get an error in version 2.1.1? If you do, can you post a screenshot from that version?

ok so it seems like the issue was that I didnt have USB debugging enabled
