### ISSUE TITLE
Feature request: Access SD card

### ISSUE THREAD

**Issue by audiamus** [GustavLindberg99/AndroidDrive#18]
So far, so good. Followed the excellent documentation and got the Android device internal storage mounted as a local disk.

Unfortunately, it does not mount the uSD card in the device. Could this be added?

**Comment by anmac1789** [comment]
> So far, so good. Followed the excellent documentation and got the Android device internal storage mounted as a local disk.
> 
> Unfortunately, it does not mount the uSD card in the device. Could this be added?

I would also love to have this feature, to be sure that it preserves all files INCLUDING FOLDERS date created, date modified and date accessed metadata. This is so extremely important

**Comment by GustavLindberg99** [comment]
It could probably be added, but my phone does not have a uSD card so I would have to borrow someone else's. So I will probably fix this, but not right away.

**Comment by anmac1789** [comment]
Who knows later on in time, micro sd cards or a related technology could return

**Comment by audiamus** [comment]
> So I will probably fix this, but not right away.

That would be really great! My latest phone doesn't have an uSD card either, but my Android tablet does and I would like to keep that in sync, too.

**Comment by audiamus** [comment]
Thanks so much, absolutely brilliant! 👍 

Now I can use robocopy. Unfortunately, Android appears to reset the file date to the current time and I need work around this. Presumably not something AndroidDrive can alter?

**Comment by anmac1789** [comment]
> Thanks so much, absolutely brilliant! 👍
> 
> Now I can use robocopy. Unfortunately, Android appears to reset the file date to the current time and I need work around this. Presumably not something AndroidDrive can alter?

wait what do u mean? clarify ?

**Comment by GustavLindberg99** [comment]
> Unfortunately, Android appears to reset the file date to the current time and I need work around this. Presumably not something AndroidDrive can alter?

That was a bug, thanks for reporting it. It's fixed in the latest version.

**Comment by audiamus** [comment]
> That was a bug, thanks for reporting it. It's fixed in the latest version.

Perfect! 👍 

_A suggestion: Why don't you move the installer exe to the Releases section? It would be more in line with GitHub conventions and you are able to get download statistics and stuff more easily._ 

_I believe that **AndroidDrive** is an excellent piece of software and should gain much more popularity. Have you considered promoting it on Reddit, for instance?_
