### ISSUE TITLE
Winrar - A device attached to the system is not functioning when using android drive

### ISSUE THREAD

**Issue by anmac1789** [GustavLindberg99/AndroidDrive#20]
When I use winrar to make a zip file and zip a folder, I receive this message:

![image](https://github.com/GustavLindberg99/AndroidDrive/assets/103609429/03631617-c8e8-4caf-b8ce-c3cbcd50d820)

**Comment by anmac1789** [comment]
Hi, its me again, I mounted my pixel 7 and wanted to zip a file thats 3.29 GB in size using winrar

![image](https://github.com/GustavLindberg99/AndroidDrive/assets/103609429/6742f0c3-ca74-46a6-8577-708e603261af)

I have 5.04 GB available so I thought I had enough space available

![image](https://github.com/GustavLindberg99/AndroidDrive/assets/103609429/e3d0715b-a3be-4ad8-af9f-a875a90f00bd)

When I use winrar to zip this file, winrar reports:

![image](https://github.com/GustavLindberg99/AndroidDrive/assets/103609429/760d8eff-ca36-4220-98f0-3f0fa63288cc)

Then I see my C drive and its run out of disk space:

![image](https://github.com/GustavLindberg99/AndroidDrive/assets/103609429/93ec60a0-d668-4c2a-9718-3669f772d513)

What's going on here...

**Comment by GustavLindberg99** [comment]
I'm working on it, please be patient.

**Comment by anmac1789** [comment]
> No problem. I didn't reply because I'm not sure exactly what's causing the bug yet, so I don't really have much to say about it right now.

ok … this app is so close to perfection besudes the massive iverhead from temporary files even after android drive has finished doing its thing and the 2GB file size limit

**Comment by anmac1789** [comment]
I did notice that whenever i start android drive, windows antimalware executable cpu usage becomes very very high

**Comment by GustavLindberg99** [comment]
This has been fixed in the latest version.
