### ISSUE TITLE
SD card not detected

### ISSUE THREAD

**Issue by tmprnc** [GustavLindberg99/AndroidDrive#26]
I am particularly opposed to using music streaming platforms, so all of my music is stored on my computer. In order to fit it into a ~192GB micro SD that I had purchased for that explicit purpose some years back, I convert everything down to OGG for the best quality to size ratio.
Problematically, having roughly 21,000 music tracks often leads to organization and file tagging mishaps. So it is not uncommon that I simply reorganize the library and then reconvert everything. In order to avoid duplicates, I tend to delete everything and re-transfer everything (which is not ideal, as it pointlessly uses up writes on the SD card).
I have changed computers recently, and the new PC problematically is no longer a laptop but a tower PC which lacks an SD card reader, so I can't directly put in the SD card. I have purchased one for that purpose, but it has yet to arrive.

Most of the software I would like to use that would save time (WinMerge would let me see diffs between the files in my phone and the original conversion folder to avoid duplicates, better copy handlers such as TeraCopy, FastCopy, or RoboCopy that would presumably shrink down the transfer times significantly) likewise can't handle a destination that's managed by MTP. For that reason, AndroidDrive is just about the perfect tool for all of my use cases.

Unfortunately, it seems that while everything is set up properly (Dokan is installed, Android USB debugging is turned on and permitted, the phone is plugged in), AndroidDrive can only detect and mount the internal filesystem, and not the inserted micro SD, as you can see:

![1708356359](https://github.com/GustavLindberg99/AndroidDrive/assets/3785923/96c57139-514f-44ad-9702-b5a81e2344a4)

The phone is a Samsung Galaxy S8 (SM-G950U1), running on Android 9. It is plugged in via a USB 3.0 port.
The PC runs on Windows 11 Pro, build 10.0.22635.3209.

Here is possibly relevant OS information:
![Screenshot_20240219-163742_Settings](https://github.com/GustavLindberg99/AndroidDrive/assets/3785923/696126b8-055a-46bc-8502-307312e37a0a)

**Comment by tmprnc** [comment]
Oh, my apologies for my previous reply. I forgot to type some of the flags you asked to use.

![1708376943](https://github.com/GustavLindberg99/AndroidDrive/assets/3785923/6830dd3c-c2ed-4761-bcbe-228c17aafcb4)

`
> adb.exe shell df /sdcard
Filesystem     1K-blocks     Used Available Use% Mounted on
/data/media     55863492 36391644  19471848  66% /storage/emulated
`

**Comment by GustavLindberg99** [comment]
This should be fixed in the latest version.

The problem was that AndroidDrive couldn't tell that your SD card was an SD card as opposed to a system folder. Normally all SD cards are listed when you do `adb shell df`, but so are system folders, and it can be tricky to tell which is which. What I did before was check which ones had the same filesystem as the internal storage, but in your case your internal storage and your SD card have different filesystems so that didn't work. Now what it does is that it assumes that SD cards either have the same filesystem as the internal storage or they have a filesystem that starts with `/mnt` and contains `media`, which should work in your case.

**Comment by tmprnc** [comment]
Can confirm it works. Thank you very much.
![1708884489](https://github.com/GustavLindberg99/AndroidDrive/assets/3785923/d51d99a6-747e-48b3-af74-e1b647016f28)
