### ISSUE TITLE
Device emulator-5562 is offline

### ISSUE THREAD

**Issue by pastortrev** [GustavLindberg99/AndroidDrive#31]
getting this error popping up over and over again. It does seem to be connecting properly but having similar issues with corrupted files. 
![Screenshot 2024-05-31 194813](https://github.com/GustavLindberg99/AndroidDrive/assets/159805258/b19c654b-1d1f-455e-b60a-7a5ab0eccd13)

**Comment by GustavLindberg99** [comment]
This is a problem with ADB, not AndroidDrive. AndroidDrive calls ADB to access your device, and for some reason ADB is returning that your device is offline so AndroidDrive can't access it.

[This page](https://stackoverflow.com/q/14993855/4284627) might have some ways you can solve this (to run ADB manually, open the command prompt and do `cd "C:\Program Files\AndroidDrive"`, then you can run commands beginning with `adb`).
