### ISSUE TITLE
Not working properly

### ISSUE THREAD

**Issue by rajdeep2k1** [GustavLindberg99/AndroidDrive#33]
Hi,
Firstly thanks for the project.
I am using Windows 11 and it is updated as on date .
My phone is not properly working as drive.
Pls see Screenshot and kindly provide solution.
![Ss](https://github.com/user-attachments/assets/588d73a4-c773-4ba0-833d-16b73118ad0c)

**Comment by GustavLindberg99** [comment]
Have you enabled USB debugging?

If you haven't, you need to enable it as explained [here](https://github.com/GustavLindberg99/AndroidDrive/blob/main/README.md#setup).

If you have, what do you get if you run the following commands in the command line?

```
cd "C:\Program Files\AndroidDrive"
adb.exe devices
adb.exe shell ls /sdcard
```

(If you installed AndroidDrive at a different location than C:\Program Files\AndroidDrive, make sure to use the correct path on the first line.)

**Comment by rajdeep2k1** [comment]
Thanks for the mail.
USB debugging is enabled.
[image: image.png]

**Comment by GustavLindberg99** [comment]
I can't see the image.

**Comment by GustavLindberg99** [comment]
This is likely due to your Android device being unauthorized. I updated it to give a more descriptive error message which explains what should be done to fix this.
