### ISSUE TITLE
Samsung Galaxy A25 is not recognized

### ISSUE THREAD

**Issue by Micccza** [GustavLindberg99/AndroidDrive#34]
Windows 10 (v10.0.19045.4780)

My smartphone will not be mounted as a drive.

1. I installed AndroidDrive 2.2.3
2. I installed Dokan
3. I activated USB debugging
4. I started AndroidDrive
5. i connected my Samsung Galaxy A25
6. My smartphone is only displayed at the windows explorer without drive letter (same as before)
7. The AndroidDrive drive list is empty

Any ideas?

PS: i did another test with my older Samsung Galaxy A23 and got the same result: not drive letter connection

**Comment by GustavLindberg99** [comment]
What happens if you run this in a command prompt?

```
cd "C:\Program Files\AndroidDrive"
adb.exe devices
```

**Comment by Micccza** [comment]
C:\Users\mt>cd "C:\Program Files\AndroidDrive"

C:\Program Files\AndroidDrive>adb.exe devices
List of devices attached


C:\Program Files\AndroidDrive>

**Comment by Micccza** [comment]
I did another test on my Win11 gaming pc with my Samsung Galaxy A5, A23 & A25. Windows recognized all 3 phones and show them at the windows explorer. The device list of AndroidDevice is always empty and no phone is connected with a drive letter.

Any ideas?

**Comment by GustavLindberg99** [comment]
This is an issue with ADB, not with AndroidDrive. You might be able to find solutions here: https://stackoverflow.com/q/21170392/4284627

Also you say that the device appears without a drive letter, which means that MTP is enabled. It's a good idea to disable it when using AndroidDrive. To do so, go to Settings > System > Advanced > Developer options > Default USB configuration > No data transfer.

**Comment by Micccza** [comment]
Sorry, it was my fault. I activated the developer mode but not the USB debugging :(
It works now!
