### ISSUE TITLE
Building file list produces error...and drive doesn't mount

### ISSUE THREAD

**Issue by jm183** [GustavLindberg99/AndroidDrive#4]
Hi,
I've launched AndroidDrive as standalone .exe. I have a HTC U12+ running Android 9 (2.60.89.3)

I'm launching the exe and connecting the device as USB. I'm getting the following error : 
![image](https://user-images.githubusercontent.com/104099467/164312326-45fe8dde-ac35-4362-824d-e41bd5442b23.png)
After opening the main window and clicking Connect Device ("Open newly connected drives in Explorer" is ticked), i get more or less the same error, more verbose though : 
![image](https://user-images.githubusercontent.com/104099467/164312750-aa3c73df-b2e7-4c34-b330-023b9403a0f3.png)

Might be important to know that i have allowed the RSA fingerprint for that device before, as it's not the first time i'm connecting my phone. Also USB mode is set to File transfer.

**Comment by GustavLindberg99** [comment]
This should be fixed in version 2. The errors you describe are related to temporary files, and AndroidDrive 2 no longer uses temporary files as extensively.
