### ISSUE TITLE
Installer - Inno Setup script issues

### ISSUE THREAD

**Issue by bovirus** [GustavLindberg99/AndroidDrive#9]
@GustavLindberg99 

Please check screenshot

- Installer exe file properties

![image](https://github.com/GustavLindberg99/AndroidDrive/assets/1262554/d71774fe-bf99-41d4-b1ad-7178be1dc480)

Missing file version
Missing copyright info

- Windows program list

![image](https://github.com/GustavLindberg99/AndroidDrive/assets/1262554/629ca742-2b28-4b65-b564-6814abd6bfdd)

Icon is not grafic icon
"version" is not necessary in program description

- Main caption of installer

![image](https://github.com/GustavLindberg99/AndroidDrive/assets/1262554/49b6cc11-1246-43e1-a139-4fd08dad34cf)

"version" is not necessary

- Info

Are you using Inno Setup 6.x?
What's the company name that you want to see in Copyright info?
Do you prefere a single last year copyright info (ex. (c) 2023 GustavLindberg99) or a copyright with startyear lastyear (ex. (c) 2017-2023 GustavLindberg99)?
In this case what's the starting year?

**Comment by GustavLindberg99** [comment]
Improving the installer script isn't a priority so I have no immediate plans to fix these things myself, but if you want you can help me improve it by creating a pull request.

> Are you using Inno Setup 6.x?

I'm using Inno Setup 6.2.2.

> What's the company name that you want to see in Copyright info? Do you prefer a single last year copyright info (ex. (c) 2023 GustavLindberg99) or a copyright with startyear lastyear (ex. (c) 2017-2023 GustavLindberg99)? In this case what's the starting year?

I don't have a company, so the name in the copyright should just be my name, Gustav Lindberg. I created the first version of AndroidDrive in 2021, so the starting year should be 2021. So the copyright should be `(c) 2021-2023 Gustav Lindberg`.

**Comment by bovirus** [comment]
@GustavLindberg99 

I prepared the changes in Inno Setup script.

What do you think as already project based on .iss to move all langauges definition/custom messages like 

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "french";  MessagesFile: "compiler:Languages\French.isl"
Name: "italian"; MessagesFile: "compiler:Languages\Italian.isl"

in a  separate .iss (ex. androiddrive-setup-languages.iss)?

Then when you want to change someting in languages (ex. add a new language) you don't touch main .iss scripèt.
